package br.com.m4rc310.budget.services;


public interface MConst {
	public static final String ACRONYM$state                    = "${acronym.state}";
	public static final String CODE$auth_user                   = "${code.auth.user}";
	public static final String CODE$ibge                        = "${code.ibge}";
	public static final String CODE$local                       = "${code.local}";
	public static final String DATE$sunrise                     = "${date.sunrise}";
	public static final String DATE$sunset                      = "${date.sunset}";
	public static final String DESC$acronym_state               = "${desc.acronym.state}";
	public static final String DESC$code_auth_user              = "${desc.code.auth.user}";
	public static final String DESC$code_ibge                   = "${desc.code.ibge}";
	public static final String DESC$code_local                  = "${desc.code.local}";
	public static final String DESC$date_sunrise                = "${desc.date.sunrise}";
	public static final String DESC$date_sunset                 = "${desc.date.sunset}";
	public static final String DESC$description_location        = "${desc.description.location}";
	public static final String DESC$field_city                  = "${desc.field.city}";
	public static final String DESC$list_district               = "${desc.list.district}";
	public static final String DESC$list_roles                  = "${desc.list.roles}";
	public static final String DESC$name_city                   = "${desc.name.city}";
	public static final String DESC$name_district               = "${desc.name.district}";
	public static final String DESC$name_username               = "${desc.name.username}";
	public static final String DESC$number_lat                  = "${desc.number.lat}";
	public static final String DESC$number_lon                  = "${desc.number.lon}";
	public static final String DESC$quantity_precipitation      = "${desc.quantity.precipitation}";
	public static final String DESC$quantity_temp               = "${desc.quantity.temp}";
	public static final String DESC$query_auth_user             = "${desc.query.auth.user}";
	public static final String DESC$query_city                  = "${desc.query.city}";
	public static final String DESC$query_locations             = "${desc.query.locations}";
	public static final String DESC$query_number_version        = "${desc.query.number.version}";
	public static final String DESC$type_auth_user              = "${desc.type.auth.user}";
	public static final String DESC$type_city                   = "${desc.type.city}";
	public static final String DESC$type_district               = "${desc.type.district}";
	public static final String DESC$type_location               = "${desc.type.location}";
	public static final String DESC$value_temp                  = "${desc.value.temp}";
	public static final String DESCRIPTION$location             = "${description.location}";
	public static final String FIELD$city                       = "${field.city}";
	public static final String INDICATOR$account_non_locked     = "${indicator.account.non.locked}";
	public static final String INDICATOR$credentials_non_locked = "${indicator.credentials.non.locked}";
	public static final String INDICATOR$enabled                = "${indicator.enabled}";
	public static final String INDICATOR$non_expired            = "${indicator.non.expired}";
	public static final String LIST$district                    = "${list.district}";
	public static final String LIST$roles                       = "${list.roles}";
	public static final String NAME$city                        = "${name.city}";
	public static final String NAME$district                    = "${name.district}";
	public static final String NAME$username                    = "${name.username}";
	public static final String NUMBER$lat                       = "${number.lat}";
	public static final String NUMBER$lon                       = "${number.lon}";
	public static final String QUANTITY$precipitation           = "${quantity.precipitation}";
	public static final String QUANTITY$temp                    = "${quantity.temp}";
	public static final String QUERY$auth_user                  = "${query.auth.user}";
	public static final String QUERY$city                       = "${query.city}";
	public static final String QUERY$locations                  = "${query.locations}";
	public static final String QUERY$number_version             = "${query.number.version}";
	public static final String TYPE$auth_user                   = "${type.auth.user}";
	public static final String TYPE$city                        = "${type.city}";
	public static final String TYPE$district                    = "${type.district}";
	public static final String TYPE$location                    = "${type.location}";
	public static final String VALUE$password                   = "${value.password}";
}

